/**
 * Shell Completion Generators
 *
 * Generates shell completion scripts for bash, zsh, fish, and PowerShell.
 *
 * @module cli-generator/completions
 */

import type { ParsedNoun, CLIConfig, ShellType } from './types'

/**
 * Generate completion command code
 */
export function generateCompletionCommand(config: CLIConfig, nouns: ParsedNoun[]): string {
  return `/**
 * Completion Command
 *
 * Generate shell completion scripts.
 */

import { Command } from 'commander'
import { color } from '../output'

const BASH_COMPLETION = \`${generateBashCompletion(config, nouns).replace(/`/g, '\\`').replace(/\$/g, '\\$')}\`

const ZSH_COMPLETION = \`${generateZshCompletion(config, nouns).replace(/`/g, '\\`').replace(/\$/g, '\\$')}\`

const FISH_COMPLETION = \`${generateFishCompletion(config, nouns).replace(/`/g, '\\`').replace(/\$/g, '\\$')}\`

const POWERSHELL_COMPLETION = \`${generatePowerShellCompletion(config, nouns).replace(/`/g, '\\`').replace(/\$/g, '\\$')}\`

export const completionCommand = new Command('completion')
  .description('Generate shell completion script')
  .argument('<shell>', 'Shell type (bash, zsh, fish, powershell)')
  .option('--install', 'Show installation instructions')
  .action((shell, options) => {
    const shellLower = shell.toLowerCase()

    let script: string
    let installInstructions: string

    switch (shellLower) {
      case 'bash':
        script = BASH_COMPLETION
        installInstructions = \`
To install bash completions:

1. Save the completion script:
   ${config.cliName} completion bash > ~/.${config.cliName}-completion.bash

2. Add to your ~/.bashrc:
   source ~/.${config.cliName}-completion.bash

3. Restart your shell or run:
   source ~/.bashrc
\`
        break

      case 'zsh':
        script = ZSH_COMPLETION
        installInstructions = \`
To install zsh completions:

1. Save the completion script:
   ${config.cliName} completion zsh > ~/.zsh/completions/_${config.cliName}

2. Ensure completions are enabled in ~/.zshrc:
   fpath=(~/.zsh/completions \\$fpath)
   autoload -Uz compinit && compinit

3. Restart your shell or run:
   source ~/.zshrc
\`
        break

      case 'fish':
        script = FISH_COMPLETION
        installInstructions = \`
To install fish completions:

1. Save the completion script:
   ${config.cliName} completion fish > ~/.config/fish/completions/${config.cliName}.fish

2. Restart your shell or run:
   source ~/.config/fish/config.fish
\`
        break

      case 'powershell':
      case 'pwsh':
        script = POWERSHELL_COMPLETION
        installInstructions = \`
To install PowerShell completions:

1. Add to your PowerShell profile ($PROFILE):
   ${config.cliName} completion powershell >> $PROFILE

2. Restart PowerShell or run:
   . $PROFILE
\`
        break

      default:
        console.error(color.error(\`Unknown shell: \${shell}\`))
        console.error(color.dim('Supported shells: bash, zsh, fish, powershell'))
        process.exit(1)
    }

    if (options.install) {
      console.log(color.info(installInstructions))
    } else {
      console.log(script)
    }
  })
`
}

/**
 * Generate Bash completion script
 */
export function generateBashCompletion(config: CLIConfig, nouns: ParsedNoun[]): string {
  const commands = ['login', 'logout', 'config', 'completion', ...nouns.map(n => n.cliName)]
  const crudCommands = ['list', 'get', 'create', 'update', 'delete']

  return `# Bash completion for ${config.cliName}
# Generated by saaskit CLI generator

_${config.cliName.replace(/-/g, '_')}_completions()
{
    local cur prev words cword
    _init_completion || return

    local commands="${commands.join(' ')}"
    local crud_commands="${crudCommands.join(' ')}"

    # Handle first argument (main command)
    if [[ \${cword} -eq 1 ]]; then
        COMPREPLY=( $(compgen -W "\${commands}" -- "\${cur}") )
        return
    fi

    # Handle subcommands
    case "\${words[1]}" in
        config)
            if [[ \${cword} -eq 2 ]]; then
                COMPREPLY=( $(compgen -W "get set delete path reset" -- "\${cur}") )
            elif [[ \${cword} -eq 3 && "\${words[2]}" == "get" ]]; then
                COMPREPLY=( $(compgen -W "baseUrl outputFormat color limit" -- "\${cur}") )
            elif [[ \${cword} -eq 3 && "\${words[2]}" == "set" ]]; then
                COMPREPLY=( $(compgen -W "baseUrl outputFormat color limit" -- "\${cur}") )
            elif [[ \${cword} -eq 3 && "\${words[2]}" == "delete" ]]; then
                COMPREPLY=( $(compgen -W "baseUrl outputFormat color limit" -- "\${cur}") )
            fi
            ;;
        completion)
            if [[ \${cword} -eq 2 ]]; then
                COMPREPLY=( $(compgen -W "bash zsh fish powershell" -- "\${cur}") )
            fi
            ;;
${nouns.map(noun => `        ${noun.cliName})
            if [[ \${cword} -eq 2 ]]; then
                COMPREPLY=( $(compgen -W "\${crud_commands} ${noun.verbs.join(' ')}" -- "\${cur}") )
            fi
            ;;`).join('\n')}
    esac
}

complete -F _${config.cliName.replace(/-/g, '_')}_completions ${config.cliName}
`
}

/**
 * Generate Zsh completion script
 */
export function generateZshCompletion(config: CLIConfig, nouns: ParsedNoun[]): string {
  const cliFunc = config.cliName.replace(/-/g, '_')

  return `#compdef ${config.cliName}
# Zsh completion for ${config.cliName}
# Generated by saaskit CLI generator

_${cliFunc}() {
    local line state

    _arguments -C \\
        "1: :->command" \\
        "*::arg:->args"

    case "\$state" in
        command)
            _values 'command' \\
                'login[Authenticate with ${config.cliName}]' \\
                'logout[Log out and remove credentials]' \\
                'config[Manage configuration]' \\
                'completion[Generate shell completion script]' \\
${nouns.map(noun => `                '${noun.cliName}[Manage ${noun.pluralName}]'`).join(' \\\n')}
            ;;
        args)
            case "\$line[1]" in
                config)
                    _values 'config subcommand' \\
                        'get[Get configuration value]' \\
                        'set[Set configuration value]' \\
                        'delete[Delete configuration value]' \\
                        'path[Show config file path]' \\
                        'reset[Reset to defaults]'
                    ;;
                completion)
                    _values 'shell' bash zsh fish powershell
                    ;;
${nouns.map(noun => `                ${noun.cliName})
                    _values '${noun.cliName} subcommand' \\
                        'list[List ${noun.pluralName}]' \\
                        'get[Get a ${noun.name.toLowerCase()} by ID]' \\
                        'create[Create a new ${noun.name.toLowerCase()}]' \\
                        'update[Update a ${noun.name.toLowerCase()}]' \\
                        'delete[Delete a ${noun.name.toLowerCase()}]'${noun.verbs.length > 0 ? ` \\
${noun.verbs.map(v => `                        '${v}[${v.charAt(0).toUpperCase() + v.slice(1)} a ${noun.name.toLowerCase()}]'`).join(' \\\n')}` : ''}
                    ;;`).join('\n')}
            esac
            ;;
    esac
}

_${cliFunc} "$@"
`
}

/**
 * Generate Fish completion script
 */
export function generateFishCompletion(config: CLIConfig, nouns: ParsedNoun[]): string {
  const lines: string[] = [
    `# Fish completion for ${config.cliName}`,
    `# Generated by saaskit CLI generator`,
    '',
    `# Disable file completion by default`,
    `complete -c ${config.cliName} -f`,
    '',
    `# Main commands`,
    `complete -c ${config.cliName} -n "__fish_use_subcommand" -a login -d "Authenticate with ${config.cliName}"`,
    `complete -c ${config.cliName} -n "__fish_use_subcommand" -a logout -d "Log out and remove credentials"`,
    `complete -c ${config.cliName} -n "__fish_use_subcommand" -a config -d "Manage configuration"`,
    `complete -c ${config.cliName} -n "__fish_use_subcommand" -a completion -d "Generate shell completion"`,
  ]

  for (const noun of nouns) {
    lines.push(`complete -c ${config.cliName} -n "__fish_use_subcommand" -a ${noun.cliName} -d "Manage ${noun.pluralName}"`)
  }

  lines.push('')
  lines.push('# Config subcommands')
  lines.push(`complete -c ${config.cliName} -n "__fish_seen_subcommand_from config" -a get -d "Get configuration value"`)
  lines.push(`complete -c ${config.cliName} -n "__fish_seen_subcommand_from config" -a set -d "Set configuration value"`)
  lines.push(`complete -c ${config.cliName} -n "__fish_seen_subcommand_from config" -a delete -d "Delete configuration value"`)
  lines.push(`complete -c ${config.cliName} -n "__fish_seen_subcommand_from config" -a path -d "Show config file path"`)
  lines.push(`complete -c ${config.cliName} -n "__fish_seen_subcommand_from config" -a reset -d "Reset to defaults"`)

  lines.push('')
  lines.push('# Completion subcommands')
  lines.push(`complete -c ${config.cliName} -n "__fish_seen_subcommand_from completion" -a "bash zsh fish powershell"`)

  for (const noun of nouns) {
    lines.push('')
    lines.push(`# ${noun.name} subcommands`)
    lines.push(`complete -c ${config.cliName} -n "__fish_seen_subcommand_from ${noun.cliName}" -a list -d "List ${noun.pluralName}"`)
    lines.push(`complete -c ${config.cliName} -n "__fish_seen_subcommand_from ${noun.cliName}" -a get -d "Get a ${noun.name.toLowerCase()}"`)
    lines.push(`complete -c ${config.cliName} -n "__fish_seen_subcommand_from ${noun.cliName}" -a create -d "Create a ${noun.name.toLowerCase()}"`)
    lines.push(`complete -c ${config.cliName} -n "__fish_seen_subcommand_from ${noun.cliName}" -a update -d "Update a ${noun.name.toLowerCase()}"`)
    lines.push(`complete -c ${config.cliName} -n "__fish_seen_subcommand_from ${noun.cliName}" -a delete -d "Delete a ${noun.name.toLowerCase()}"`)

    for (const verb of noun.verbs) {
      lines.push(`complete -c ${config.cliName} -n "__fish_seen_subcommand_from ${noun.cliName}" -a ${verb} -d "${verb.charAt(0).toUpperCase() + verb.slice(1)} a ${noun.name.toLowerCase()}"`)
    }
  }

  return lines.join('\n')
}

/**
 * Generate PowerShell completion script
 */
export function generatePowerShellCompletion(config: CLIConfig, nouns: ParsedNoun[]): string {
  const commands = ['login', 'logout', 'config', 'completion', ...nouns.map(n => n.cliName)]
  const crudCommands = ['list', 'get', 'create', 'update', 'delete']

  return `# PowerShell completion for ${config.cliName}
# Generated by saaskit CLI generator

Register-ArgumentCompleter -Native -CommandName ${config.cliName} -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)

    $commands = @(${commands.map(c => `'${c}'`).join(', ')})
    $crudCommands = @(${crudCommands.map(c => `'${c}'`).join(', ')})

    $elements = $commandAst.CommandElements
    $command = $elements[0].Value

    # First argument completion
    if ($elements.Count -eq 1 -or ($elements.Count -eq 2 -and $elements[1].Value -eq $wordToComplete)) {
        $commands | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
            [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
        }
        return
    }

    $subCommand = $elements[1].Value

    switch ($subCommand) {
        'config' {
            if ($elements.Count -eq 2 -or ($elements.Count -eq 3 -and $elements[2].Value -eq $wordToComplete)) {
                @('get', 'set', 'delete', 'path', 'reset') | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
                    [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
                }
            }
        }
        'completion' {
            if ($elements.Count -eq 2 -or ($elements.Count -eq 3 -and $elements[2].Value -eq $wordToComplete)) {
                @('bash', 'zsh', 'fish', 'powershell') | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
                    [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
                }
            }
        }
${nouns.map(noun => `        '${noun.cliName}' {
            if ($elements.Count -eq 2 -or ($elements.Count -eq 3 -and $elements[2].Value -eq $wordToComplete)) {
                @($crudCommands + @(${noun.verbs.map(v => `'${v}'`).join(', ')})) | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
                    [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
                }
            }
        }`).join('\n')}
    }
}
`
}

/**
 * Get shell completion script for a specific shell type
 */
export function getCompletionScript(
  shell: ShellType,
  config: CLIConfig,
  nouns: ParsedNoun[]
): string {
  switch (shell) {
    case 'bash':
      return generateBashCompletion(config, nouns)
    case 'zsh':
      return generateZshCompletion(config, nouns)
    case 'fish':
      return generateFishCompletion(config, nouns)
    case 'powershell':
      return generatePowerShellCompletion(config, nouns)
    default:
      throw new Error(`Unsupported shell: ${shell}`)
  }
}
